[project]
protostar-version = "0.14.0"

[contracts]
hello_starknet = ["src"]

# Per command configuration profile
[profile.integration.test]
target = ["tests/integration"]
report-slowest-tests = 5

# Shared configration profile
[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321

[profile.testnet.project]
network = "testnet"

["profile.testnet.protostar.deploy"]
network = "testnet"

["profile.devnet.protostar.deploy"]
gateway-url = "http://127.0.0.1:5050/"